### ISSUE TITLE
Circuit Breaker port conflict

### ISSUE THREAD

**Issue by lduparc** [VanRoy/spring-cloud-dashboard#20]
Hi @VanRoy 

I'm trying to enable turbine with spring-cloud-dashboard.

I add the dependencies : 
```
turbineStream         : "org.springframework.cloud:spring-cloud-starter-turbine-stream",
rabbitStream          : "org.springframework.cloud:spring-cloud-starter-stream-rabbit",
```
on my Application.java:

```
@EnableTurbineStream
```

on my config: 

```
spring:
  cloud:
    dashboard:
      turbine:
        url: http://${discovery.host}:8989/turbine.stream
```

But the application failed to start. If I remove turbine, everything works fine. How can fix it ? The error is always the same : 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port XXXX was already in use.
```
