### ISSUE TITLE
Fail to load home page

### ISSUE THREAD

**Issue by lduparc** [VanRoy/spring-cloud-dashboard#21]
Hi,

I have a stack of more than 100 microservices. With a bunch of microservices the home page is not able to load  and we can see the loader undeterminately.

**Comment by VanRoy** [comment]
Hi @lduparc , what backend do you use ? Eureka or Beanstalk ?

**Comment by lduparc** [comment]
Hi @VanRoy ,

I'm using eureka as backend.
Here my configuration.

```
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    # hostname: ${spring.application.name}
    virtualHostName: ${spring.application.name}
    metadataMap:
      instanceId: ${EUREKA_INSTANCE_ID:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true
  dashboard:
    enabled: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eurekaConnectionIdleTimeoutSeconds: 30
    eurekaServerConnectTimeoutSeconds: 30
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${discovery.host}:${discovery.port}/eureka/
```
